name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:ubuntu${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        distro: ['22.04', '20.04', '18.04']
        flag: ['-j']
        include:
          - distro: '16.04'
            flag: '-j1'


    name: ubuntu${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make ${{ matrix.flag }}

      - name: Run unit test
        run: ./build/bin/unittests